name: Formatting Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  python-format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code (as submodule from experiments/base)"
        uses: actions/checkout@v3
      # Formatting checks
      - name: "Code formatting check"
        run: ./bin/inv_wrapper.sh format-code
